import type { Metadata } from 'next';
import GroupDescription from './_component/GroupDescription';
import GroupAddress from './_component/GroupAddress';
import TimeUntilStart from './_component/TimeUntilStart';
import GroupTime from './_component/GroupTime';
import { ButtonGroup } from './_component/ButtonGroup';
import GroupMembers from './_component/GroupMembers';

export const metadata: Metadata = {
  title: '그룹',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  location
}: Readonly<{
  children: React.ReactNode,
  location: React.ReactNode;
}>) {
  const groupData = {
    host: {
      memberId: 1,
      imgUrl: 'https://fakeimg',
      nickname: '아모르겠고',
      moGakCoTemperature: 0,
      githubUrl: null,
    },
    name: 'AmorGakCo',
    description: '모각코 합시다.',
    address: '서울특별시 종로구 신문로1가 23',
    longitude: 126.9748397,
    latitude: 37.5703901,
    beginAt: '2024-08-25T22:40:04.101337',
    endAt: '2024-08-25T23:55:04.101342',
    groupMembers: [
      {
        memberId: 1,
        imgUrl: '/coin.svg',
        nickname: '아모르겠고',
        moGakCoTemperature: 0,
        githubUrl: null,
      },
      {
        memberId: 2,
        imgUrl: '/coin.svg',
        nickname: '아모르겠고',
        moGakCoTemperature: 0,
        githubUrl: null,
      },
      {
        memberId: 3,
        imgUrl: '/coin.svg',
        nickname: '아모르겠고',
        moGakCoTemperature: 0,
        githubUrl: null,
      },
      {
        memberId: 4,
        imgUrl: '/coin.svg',
        nickname: '아모르겠고',
        moGakCoTemperature: 0,
        githubUrl: null,
      },
      {
        memberId: 5,
        imgUrl: '/coin.svg',
        nickname: '아모르겠고',
        moGakCoTemperature: 0,
        githubUrl: null,
      },
      {
        memberId: 6,
        imgUrl: '/coin.svg',
        nickname: '아모르겠고',
        moGakCoTemperature: 0,
        githubUrl: null,
      },
      {
        memberId: 7,
        imgUrl: '/coin.svg',
        nickname: '아모르겠고',
        moGakCoTemperature: 0,
        githubUrl: null,
      },
      {
        memberId: 8,
        imgUrl: '/coin.svg',
        nickname: '아모르겠고',
        moGakCoTemperature: 0,
        githubUrl: null,
      },
      {
        memberId: 9,
        imgUrl: '/coin.svg',
        nickname: '아모르겠고',
        moGakCoTemperature: 0,
        githubUrl: null,
      },
      {
        memberId: 10,
        imgUrl: '/coin.svg',
        nickname: '아모르겠고',
        moGakCoTemperature: 0,
        githubUrl: null,
      },
    ]};
  const beginAtDate = new Date(groupData.beginAt);
  const endAtDate = new Date(groupData.endAt);
  return (
    <div className="flex justify-center">
      <div className="flex flex-col min-w-[312px] w-full max-w-96 py-6 gap-6 mb-0.5">
        <GroupDescription description={groupData.description} />
        <GroupAddress address={groupData.address} />
        {children}
        {location}
        <GroupMembers groupMembers={groupData.groupMembers} />
        <TimeUntilStart beginAt={groupData.beginAt} />
        <GroupTime beginAtDate={beginAtDate} endAtDate={endAtDate} />
        <ButtonGroup name={groupData.name} />
      </div>
    </div>
  );
}
